version: '3.1'

services:
  postgres:
  image: postgres:10
  container_name: my_postgres_container
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: johndoe
    POSTGRES_PASSWORD: 123
    POSTGRESS_DB: mydb
  volumes:
    my_postgres_data:
